name: 'Horusec'
description: 'Secure Code Analysis'
inputs:
  github-token:
    description: "the token is used to search the latest Horusec version"
    default: ${{ github.token }}
    required: true
  ignore:
    description: "Paths to ignore in the analysis"
    required: false
  project-path:
    description: "Path to run an analysis in your project"
    default: "./"
    required: false
  output-format:
    description: "The format for the output to be shown"
    default: "json"
    required: false
outputs:
  result:
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
